### ISSUE TITLE
"Connection to websocket lost, re-creating session" Never reconnects

### ISSUE THREAD

**Issue by TZ122** [rtm516/MCXboxBroadcast#78] opened 2024-05-14 20:39 UTC
When I run the latest McXboxBroadcast standalone software the connection to the websocket fails to reconnect. The only way to remedy this is to exit the program and launch it again.

Log: https://pastebin.com/qNFSzNxt
Config: https://pastebin.com/A91YKPzQ

Any help is appreciated
Thanks

**Comment by TZ122** [comment] 2024-05-15 12:26
Adding my dumpsession here seems to error: https://pastebin.com/Vix4k5qP

**Comment by sennby** [comment] 2024-06-04 18:21
I couldnt get extension to work whatsoever.
Use standalone and itll work.

**Comment by rtm516** [comment] 2024-06-07 20:13
dumpsession should be fixed update and provide that output

**Comment by TZ122** [comment] 2024-06-08 13:58
> I couldnt get extension to work whatsoever. Use standalone and itll work.

This issue is occurring on standalone.

**Comment by TZ122** [comment] 2024-06-08 15:42
> dumpsession should be fixed update and provide that output

Dump session after "websocket lost, re-creating session" never reconnected.

Current session response: File was empty
Last session response: https://pastebin.com/khG3RVXj
Log: https://pastebin.com/w1kTu2v9

**Comment by rtm516** [comment] 2024-06-08 15:45
Looks like the issue is being caused by you logging into that account on a different machine. An account shouldn't be used for a game and this tool at the same time.
We suggest using a separate account for the tool

**Closed by rtm516** 2024-06-08 15:45 UTC

**Comment by TZ122** [comment] 2024-06-08 23:55
> 

Thanks I had another instance of MCxboxbroadcast geyser extension running with one of the same sub accounts and didnt notice.  👍

**Comment by TZ122** [comment] 2024-06-10 00:12
Sorry I have spoke too soon. The same happened today where the websocket never reconnected although this time it ran for 8+ hours whereas before it would crash after 30 minutes. Can you please let me know if this is the same issue? Thank you.

Current session response: File was empty
Last session response: https://pastebin.com/SjkWW3Pz
Log before crash: https://pastebin.com/ixq33LtP
Latest Log: https://pastebin.com/wzz3fyMs

**Comment by rtm516** [comment] 2024-06-10 06:53
Looks like it is the same issue
