### ISSUE TITLE
Can't open the Jenkins link

### ISSUE THREAD

**Issue by UltraHispeed-Elite** [rtm516/MCXboxBroadcast#19] opened 2023-04-05 13:46 UTC
Cannot open the link you provided in releases

**Comment by aking4125** [comment] 2023-04-08 18:18
Confirmed the link is broken:

![image](https://user-images.githubusercontent.com/11141831/230736907-a93d9065-0c55-4c28-8486-0b91ae57a05e.png)

**Comment by rtm516** [comment] 2023-04-10 11:18
This is due to my server having issues I hope to have it resolved by the end of the week.

**Closed by rtm516** 2023-04-10 11:18 UTC
