### ISSUE TITLE
Been a week

### ISSUE THREAD

**Issue by lolwhatdidigetbanned** [rtm516/MCXboxBroadcast#127] opened 2024-08-19 02:00 UTC
Been a week still no update, are you back in town to fix this issue?

**Comment by FluffoSensei** [comment] 2024-08-19 03:28
I bet he's working hard on it :) patience is key

**Comment by Astil-Industries** [comment] 2024-08-19 07:24
It's not just this what's broken lots of the server selector one sand DNS server selectors and some data packs have been broken

**Comment by rtm516** [comment] 2024-08-19 07:35
Duplicate of #122

**Closed by rtm516** 2024-08-19 07:35 UTC
