### ISSUE TITLE
The 1.21.20 update broke mcxboxbroadcast

### ISSUE THREAD

**Issue by lolwhatdidigetbanned** [rtm516/MCXboxBroadcast#124] opened 2024-08-14 01:24 UTC
Please fix it, (sorry for duplication)

**Comment by CoveWolf** [comment] 2024-08-14 02:10
He's trying to.

**Comment by HealingHalo8** [comment] 2024-08-14 02:56
hey the developer for this plugin is current out of town, but is attempting to fix it, he will have it up as soon as possible.

**Comment by rtm516** [comment] 2024-08-14 07:28
Duplicate of https://github.com/rtm516/MCXboxBroadcast/issues/122

**Closed** 2024-08-14 07:28 UTC
