### ISSUE TITLE
Outdated plugin

### ISSUE THREAD

**Issue by Gen800** [rtm516/MCXboxBroadcast#126] opened 2024-08-17 13:42 UTC
so i was trying to make a crossplay server with me and my friends, but one friend is on xbox so i tried this plugin  so when i installed it and i configured it, i tried to test it but i cant join the server cuz the plugin is in 1.21.20 and we are in 1.21.21, is there any way to fix this issue?

**Comment by onebeastchris** [comment] 2024-08-17 13:48
Duplicate of https://github.com/rtm516/MCXboxBroadcast/issues/122 - 1.21.20/1.21.21 (they're the same protocol) are currently broken. If you want to be notified when it's updated, join the discord.

**Closed by onebeastchris** 2024-08-17 13:48 UTC
