### ISSUE TITLE
MCXboxBroadcast not adding friends back

### ISSUE THREAD

**Issue by HippieBeak** [rtm516/MCXboxBroadcast#97] opened 2024-06-26 20:00 UTC
Recently, the tool has not been adding users back after it's been running for some time (say, 30 minutes). I'm not sure if this is correlated with the amount of time the tool was running, or how many users connected/were added during that time. To fix, I need to run `mcxboxbroadcast restart`, which ends up adding the friends back after about ~20 seconds. In the meantime, I've setup a schedule to run `mcxboxbroadcast restart` periodically, but not sure if this will cause any issues...

**Comment by rtm516** [comment] 2024-06-26 20:23
Duplicate of #94

Please update

**Comment by HippieBeak** [comment] 2024-06-26 20:38
This is with build 31.

**Comment by rtm516** [comment] 2024-06-26 20:58
Please enable debug logs 
- MCXB extension versions in the geyser config.yml
- MCXB standalone in `config.yml`

Also provide a session dump `mcxboxbroadcast dumpsession`

**Comment by HippieBeak** [comment] 2024-06-26 23:50
I've sent you the debug logs on Discord, as they contain PII. My discord username is `hippiebeak`.

`currentSessionResponse.json`: https://pastebin.com/fjtjrLjW
`lastSessionResponse.json`: https://pastebin.com/ugpWYkny

![Screenshot_2024-06-26_at_7](https://github.com/rtm516/MCXboxBroadcast/assets/15806196/2c3212a7-5384-42c6-98ea-3c69f9cdf17a)

**Comment by rtm516** [comment] 2024-06-27 11:27
Done some testing and looked over the logs you provided and I'm unable to replicate but can confirm your bot is having the issue.

**Comment by rtm516** [comment] 2024-08-05 09:42
Resolved as part of the manager merge build 41+ should have this fixed

Specific commit https://github.com/rtm516/MCXboxBroadcast/commit/aa3ca2e775854e507aba5ef3d61982487d62641a

**Closed** 2024-08-05 09:42 UTC
